version: 0.2

phases:
  install:
   commands:
     - npm install -g serverless
	  
  pre_buid:
   commands:
     - npm install
	 
  build:
    commands:
	 - sls deploy -v -s $ENV_NAME
	 
  post_build:
    commands:
	 - echo deployment completed
